# Generated by Django 4.2.13 on 2024-06-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_class_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='img',
            field=models.CharField(choices=[('client/src/assets/Lesson/Esp1.png', 'Esp1'), ('client/src/assets/Lesson/Esp2.png', 'Esp2'), ('client/src/assets/Lesson/Esp3.png', 'Esp3'), ('client/src/assets/Lesson/Esp4.png', 'Esp4'), ('client/src/assets/Lesson/Esp5.png', 'Esp5'), ('client/src/assets/Lesson/Esp6.png', 'Esp6'), ('client/src/assets/Lesson/Esp7.png', 'Esp7'), ('client/src/assets/Lesson/Esp8.png', 'Esp8'), ('client/src/assets/Lesson/Math1.png', 'Math1'), ('client/src/assets/Lesson/Math2.png', 'Math2'), ('client/src/assets/Lesson/Math3.png', 'Math3'), ('client/src/assets/Lesson/Math4.png', 'Math4'), ('client/src/assets/Lesson/Math5.png', 'Math5'), ('client/src/assets/Lesson/Math6.png', 'Math6'), ('client/src/assets/Lesson/Math7.png', 'Math7'), ('client/src/assets/Lesson/Math8.png', 'Math8')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.CharField(choices=[('client/src/assets/Profile/Amiko.png', 'Amiko'), ('client/src/assets/Profile/Bro.png', 'Bro'), ('client/src/assets/Profile/Pana.png', 'Pana'), ('client/src/assets/Profile/Rafiki.png', 'Rafiki')], default='client/src/assets/Profile/Cow.jpg', max_length=100),
        ),
    ]
