# Generated by Django 4.2.13 on 2024-06-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_alter_class_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='img',
            field=models.CharField(choices=[('../public/assets/Lesson/Esp1.png', 'Esp1'), ('../public/assets/Lesson/Esp2.png', 'Esp2'), ('../public/assets/Lesson/Esp3.png', 'Esp3'), ('../public/assets/Lesson/Esp4.png', 'Esp4'), ('../public/assets/Lesson/Esp5.png', 'Esp5'), ('../public/assets/Lesson/Esp6.png', 'Esp6'), ('../public/assets/Lesson/Esp7.png', 'Esp7'), ('../public/assets/Lesson/Esp8.png', 'Esp8'), ('../public/assets/Lesson/Math1.png', 'Math1'), ('../public/assets/Lesson/Math2.png', 'Math2'), ('../public/assets/Lesson/Math3.png', 'Math3'), ('../public/assets/Lesson/Math4.png', 'Math4'), ('../public/assets/Lesson/Math5.png', 'Math5'), ('../public/assets/Lesson/Math6.png', 'Math6'), ('../public/assets/Lesson/Math7.png', 'Math7'), ('../public/assets/Lesson/Math8.png', 'Math8')], max_length=100),
        ),
    ]
