# Generated by Django 4.2.13 on 2024-06-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0008_alter_class_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.CharField(choices=[('../public/assets/Profile/Amiko.png', 'Amiko'), ('../public/assets/Profile/Bro.png', 'Bro'), ('../public/assets/Profile/Pana.png', 'Pana'), ('../public/assets/Profile/Rafiki.png', 'Rafiki')], default='client/src/assets/Profile/Cow.jpg', max_length=100),
        ),
    ]
