# Generated by Django 4.2.13 on 2024-06-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0009_alter_user_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
