# Generated by Django 4.2.13 on 2024-06-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0010_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_number',
            field=models.IntegerField(default=1212),
            preserve_default=False,
        ),
    ]
